const Home=()=>{
    return(
        <div className="max-w-[1200px] mx-auto">
            <h2 className="text-[1.8rem] font-bold "><span className="text-red-600 text-[2rem] ">H</span>ome</h2>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam expedita, error nulla natus itaque obcaecati nobis facere veritatis nostrum soluta distinctio, maiores, laudantium earum tenetur tempore accusantium sed. Autem similique eligendi quibusdam nihil quasi, obcaecati natus reprehenderit nisi, eustrum sequi consequuntur pariatur quaerat nam commodi, inventore voluptatibus? Ex temporibus nisi possimus architecto, officiis molestias illum recusandae. Unde odio quam omnis, fugit, vitae sit provident aspernatur veniam eius odit asperiores repellendus similique saepe perferendis aliquid at consequatur. Nostrum maiores alias ut excepturi assumenda neque eum soluta tempora saepe amet, veritatis dolor atque illum quo magnam corporis rem.</p>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam expedita, error nulla natus itaque obcaecati nobis facere veritatis nostrum soluta distinctio, maiores, laudantium earum tenetur tempore accusantium sed. Autem similique eligendi quibusdam nihil quasi, obcaecati natus reprehenderistias illum recusandae. Unde odio quam omnis, fugit, vitae sit provident aspernatur veniam eius odit asperiores repellendus similique saepe perferendis aliquid at consequatur. Nostrum maiores alias ut excepturi assumenda neque eum soluta tempora saepe amet, veritatis dolor atque illum quo magnam corporis rem.</p>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam expedita, error nulla natus itaque obcaecati nobis facere veritatis nostrum soluta distinctio, maiores, laudantium earum tenetur tempore accusantium sed. Autem similique eligendi quibusdam nihil quasi, obcaecati natus reprehenderit nisi, eum numquam vel recusandae nostrum sequi consequuntur pariatur quaerat nam commodi, inventore voluptatibus? Ex temporibus nilique saepe perferendis aliquid at consequatur. Nostrum maiores alias ut excepturi assumenda neque eum soluta tempora saepe amet, veritatis dolor atque illum quo magnam corporis rem.</p>
        </div>
    )
}
export default Home